name: Python test
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry & dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$PATH:$HOME/.local/bin"
          poetry self update --preview
          poetry install
      - name: Run pre-commit
        run: |
          export PATH="$PATH:$HOME/.local/bin"
          source `poetry env info --path`/bin/activate
          pre-commit run --all-files
      - name: Run test
        run: |
          export PATH="$PATH:$HOME/.local/bin"
          source `poetry env info --path`/bin/activate
          pytest
